In [5]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np

In [10]:
import time 

In [12]:
arr = np.array([[2,3,4],[5,7,8]])

In [19]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

int64
2
(2, 3)


In [38]:
import time
my_list = list(range(1_00_000))
start_time = time.time()
result = []
for i in my_list:
    result.append(i + 5)
end_time = time.time()
print("it took time to execute:", end_time - start_time)

it took time to execute: 0.011727094650268555


In [39]:
import time
import numpy as np
arr = np.array(range(1_00_000))
start_time = time.time()
result_arr = arr + 5
end_time = time.time()
print("it took time to execute:", end_time - start_time)

it took time to execute: 0.001007080078125


In [40]:
import numpy as np
arr = np.array([2,4,6])
print(arr)

[2 4 6]


In [42]:
import numpy as np
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
import numpy as np
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [44]:
import numpy as np
arr = np.full((2,3), 6)
print(arr)

[[6 6 6]
 [6 6 6]]


In [47]:
import numpy as np
arr = np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [48]:
import numpy as np  #this will the given range in equal spaces
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [49]:
import numpy as np   #this will create the diagonal values one and non diagonal values 0s
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [51]:
import numpy as np    # this will craete the diagonal matrix with given diagonal values nad pace 0s for non-diagnoal values
arr = np.diag([2,3,7,8])
print(arr)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 7 0]
 [0 0 0 8]]


In [53]:
import numpy as np
arr = np.array((5,3, 23), dtype= float)
print(arr)

[ 5.  3. 23.]


In [54]:
import numpy as np
arr = np.array([3.4, 5., 7, 8.2])
print(arr.astype(int))

[3 5 7 8]


In [ ]:
import numpy as np  # this creates a 2D array from a list of lists

arr = np.array([[2, 3, 4], [5, 7, 8]])

print(arr[1, 1])  # prints the value at 0th row and 2nd column

7


In [6]:
import numpy as np  # this creates a 2D array from a list of lists

arr = np.array([[2, 3, 4, 5], [5, 7, 8, 9]])
print(arr)

print(arr[-1, -2])  # prints the value at last row and second-to-last column
print(arr[1:2, 2:3])  # slicing on the 2 domentional array 
print(arr[::2, ::2])   # print every second row and every second colimn 


[[2 3 4 5]
 [5 7 8 9]]
8
[[8]]
[[2 4]]


In [ ]:
import numpy as np  # this creates a 2D array from a list of lists

arr = np.array([[2, 3, 4, 5], [5, 7, 8, 9]])
print(arr)

new_array = arr[0:1, 1:3]
print(arr[0,1])
new_array[0, 1] = 100     # this will change the value at 0th row and 2nd column of new_array to 100 in original array
print(new_array) 
print(arr)
 # the original array is also modified because new_array is a view of arr

[[2 3 4 5]
 [5 7 8 9]]
3
[[  3 100]]
[[  2   3 100   5]
 [  5   7   8   9]]


In [15]:
import numpy as np  # this creates a 2D array from a list of lists

arr = np.array([[2, 3, 4, 5], [5, 7, 8, 9]])
print(arr)

new_array = arr[0:1, 1:3].copy() # this will create a copy of the sliced array, so changes to new_array will not affect arr
print(arr[0,1])
new_array[0, 1] = 100    
print(new_array) 
print(arr)


[[2 3 4 5]
 [5 7 8 9]]
3
[[  3 100]]
[[2 3 4 5]
 [5 7 8 9]]


In [28]:
rang = np.random.default_rng()  
flips  =  rang.integers(0, 2, size=100000)  # generate 10 random integers between 0 and 1 (inclusive)
prob_head = np.mean(flips)
print("probality heads are:", prob_head)

probality heads are: 0.49906


In [ ]:
rang = np.random.default_rng(seed=5)  # setting a seed for reproducibility for exact same random numbers every time we run the code
flips  =  rang.integers(0, 2, size=100000)  # generate 10 random integers between 0 and 1 (inclusive)
prob_head = np.mean(flips)
print("probality heads are:", prob_head)

probality heads are: 0.49889
